Testregform
juandape/frontend-topv29-restaurantes pull request #36
Opened 2023-06-02 22:20 UTC by juandape

### Descripción
[//]: <> (Aca debe ir la descripcion del PullRequest, que es? que hace?)

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <> (Pasos necesarios para probar esta funcionalidad)
``` npm run test```

### Screenshots (si es aplicable)
[//]: <>![image](https://github.com/juandape/frontend-topv29-restaurantes/assets/41099211/654c3696-d4d8-435d-a19c-2082b5418cd9)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2023-06-02 23:08 UTC, khriztianmoreno requested changes
Fusiona primero el otro Pull request para q este se vea más limpio

2023-06-02 23:08 UTC, khriztianmoreno commented on package.json
> +    "test": "vitest --watch",
No es necesario agregar el watch ya lo hace por defecto

2023-06-02 23:35 UTC, juandape commented on package.json
> +    "test": "vitest --watch",
ok corregido

2023-06-03 13:16 UTC, khriztianmoreno approved these changes

2023-06-03 13:20 UTC, merged