componente para descargar app
juandape/frontend-topv29-restaurantes pull request #65
Opened 2023-06-06 18:28 UTC by juandape

### Descripción
[//]: <> componente para el home descarga app

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [ ] 🤙 Solucion rapida
- [x] 👌 Terminado y listo
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
[//]: <> (El numero del ticket asociado a este PR)

### Cómo probar?
[//]: <>ver despliegue vercel

### Screenshots (si es aplicable)
[//]: <> ![image](https://github.com/juandape/frontend-topv29-restaurantes/assets/41099211/43f60ded-7d65-435c-aa79-36a3b9f1ba31)

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2023-06-06 21:32 UTC, lorza12 approved these changes
Excelente 👍

2023-06-06 21:50 UTC, khriztianmoreno requested changes
Solo esta pensado para desktop.

<img width="347" alt="Screen Shot 2023-06-06 at 4 48 06 PM" src="https://github.com/juandape/frontend-topv29-restaurantes/assets/1481964/092a8099-e785-486f-b3d2-54b2911c576c">

Un mejor PR seria enviar el componente que se ajuste a pantallas desktop y mobiles, asi no tendras q volver a enviar otro PR para corregir esto.

Recuerda ademas que estamos trabajando `mobile first`

2023-06-06 23:14 UTC, juandape commented
> Solo esta pensado para desktop.
> 
> <img alt="Screen Shot 2023-06-06 at 4 48 06 PM" width="347" src="https://user-images.githubusercontent.com/1481964/243840431-092a8099-e785-486f-b3d2-54b2911c576c.png">
> Un mejor PR seria enviar el componente que se ajuste a pantallas desktop y mobiles, asi no tendras q volver a enviar otro PR para corregir esto.
> 
> Recuerda ademas que estamos trabajando `mobile first`


> Solo esta pensado para desktop.
> 
> <img alt="Screen Shot 2023-06-06 at 4 48 06 PM" width="347" src="https://user-images.githubusercontent.com/1481964/243840431-092a8099-e785-486f-b3d2-54b2911c576c.png">
> Un mejor PR seria enviar el componente que se ajuste a pantallas desktop y mobiles, asi no tendras q volver a enviar otro PR para corregir esto.
> 
> Recuerda ademas que estamos trabajando `mobile first`

Ya estaba con mobile first, no se porque no te funciono
![image](https://github.com/juandape/frontend-topv29-restaurantes/assets/41099211/c0673ca3-1ff3-48fb-bbc9-2a2df97804c2)

2023-06-07 22:07 UTC, khriztianmoreno approved these changes

2023-06-07 22:11 UTC, merged